[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "https://cscwx.com/:splat"
  status = 301
  force = true
