[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  targetPort = 3000

[[redirects]]
    from = "https://csc-wx-app.netlify.app/*"
    to = "https://cscwx.com"
    status = 301
    force = true
